name: arkom_apps
description: Arif Komik Apps.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_flavorizr: ^2.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Arkom Apps Dev"

      android:
        applicationId: "ar.tools.arkom.dev"

      ios:
        bundleId: "ar.tools.arkom.dev"

    prod:
      app:
        name: "Arkom Apps"

      android:
        applicationId: "ar.tools.arkom"
      ios:
        bundleId: "ar.tools.arkom"
